### ISSUE TITLE
Start the game with a single region uncovered

### ISSUE THREAD

**Issue by ArthaTi** [JochCool/minesweeper-bot#18]
**Description of the feature**  
The bot should select a random safe region and uncover it so it's not in a spoiler. It could select a random `0` and uncover the all neighbors until no `0` has an uncovered neighbor left.

**Reason**  
Very often when I start the game I hit a mine, or have to uncover all the zeros manually. The bot could do that automatically.

Given a sample board, this is what the bot would output:
```
||:zero:|| ||:zero:|| ||:zero:|| ||:two:|| ||:bomb:||
||:one:|| ||:two:|| ||:one:|| ||:three:|| ||:bomb:||
||:bomb:|| ||:two:|| ||:bomb:|| ||:two:|| ||:one:||
```
The wanted output would be:
```
:zero: :zero: :zero: :two: ||:bomb:||
:one: :two: :one: :three: ||:bomb:||
||:bomb:|| ||:two:|| ||:bomb:|| ||:two:|| ||:one:||
```
This way the player is given a sample region and a good start, and can safely uncover the board without having to reset if they don't hit the proper tile.

**Comment by JochCool** [comment]
Hi, thank you for your suggestion. I am currently on holiday so I won't be able to implement it right now, but I will do it next week when I'm back.
