### ISSUE TITLE
/auto command

### ISSUE THREAD

**Issue by INotSleep** [JochCool/minesweeper-bot#33]
**Description of the feature**
Command, that send game in channel one time per minute

**Reason**
For automacly send game.

**Details** (optional)
I wanted to make pull request, but idk how (lol)
there code: https://github.com/INotSleep/minesweeper-bot/

**Comment by JochCool** [comment]
Hi! Thanks for all the work you've put into it. I sadly don't have time to look at it in the coming days, but I sure will do so in a week or so.

**Comment by INotSleep** [comment]
Ok.

**Comment by JochCool** [comment]
Hi @INotSleep! Sorry that this took so long, but I have now finally added the command in commit 07d395bcdc18992fac21a126db645a1507b66a82. I have changed the implementation quite a bit but the command functions basically the same. It will be in the next release, hopefully today or tomorrow.
