### ISSUE TITLE
Bot doesnt respond to any commands.

### ISSUE THREAD

**Issue by nikjust** [JochCool/minesweeper-bot#38]
**Description**
Bot doesn't respond to any commands

**To reproduce:**
1. Use any bot command

**Expected behavior**
Bot should respond to commands.

**Screenshots**
![image](https://github.com/JochCool/minesweeper-bot/assets/36077796/0f7f42dc-8af2-4973-94ac-b75eadd3de11)

**Comment by JochCool** [comment]
Hi, thanks for reporting it. This has sadly been the case for a while now, because the device that hosts the bot broke down, and I still haven't been able to fix it.

**Comment by JochCool** [comment]
The bot is no longer maintained.
