### ISSUE TITLE
Remove 'Unknown command' message

### ISSUE THREAD

**Issue by 3urobeat** [JochCool/minesweeper-bot#4]
It would be nice if you could remove the Unknown command error message because whenever i use a bot that uses the ! prefix or someone writes a single ! in his message the bot will respond with that message.
Just let the bot do nothing when a unknown command gets called - i did the same for my bots and the chat is clean and nice. You could also put the !help command in the bot's current game so everybody knows how to get your commands.
Have a nice day and thank you for creating a cool bot :)

**Comment by JochCool** [comment]
Thank you for this suggestion! The unknown command message has been removed in version 1.3.
